version: '3.0'

services:
  grafana:
    container_name: 'bos-grafanascenesplayground-scenesapp'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-10.2.0}
        livereload_host: "https:\\/\\/${CODESPACE_NAME}-35729.app.github.dev"
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/bos-grafanascenesplayground-scenesapp
      - ./provisioning:/etc/grafana/provisioning
